### ISSUE TITLE
[ESLINT(not an issue)] Unsafe member access on an any value fabric()

### ISSUE THREAD

**Issue by fabio984** [zefoy/ngx-fabric-wrapper#16]
Hi,

I'm not reporting this as an issue/error (because everything works fine), but since I installed ESLINT on my Angular project I'm getting like 200 errors (on every line where I call **fabric()**, for example:

`this.directiveRef.fabric().discardActiveObject();`

I get the ESLINT error:

**Unsafe member access .discardActiveObject on an any value**.

In _fabric.directive.d.ts_ file, at line 69, fabric is declared like this: **fabric(): any;**

Can it be changed to avoid this ESLINT errors? (or any other way to get rid of this errors?

**Comment by sconix** [comment]
I think fabric has typings nowadays, not fully sure but if thats the case I will most likely switch using those for next release.
