### ISSUE TITLE
Add all the rest of the fabric events

### ISSUE THREAD

**Issue by diosney** [zefoy/ngx-fabric-wrapper#5]
Sorry to bring this again, but I found myself in the need to use some specific fabric events that are not supported by the wrapper, maybe it is not much of a fuss to add them all?

The complete list is at http://fabricjs.com/events

Thanks!

**Comment by sconix** [comment]
Sure I can add them, in the meantime you can always get the fabric instance from the directive and register the events to it with fabrics 'on' method.

**Comment by diosney** [comment]
@sconix Indeed! That's is what I'm doing now :smile:
