### ISSUE TITLE
bug: Updating `[data]` and some properties in event like (selectionUpdated) causes `ExpressionChangedAfterItHasBeenCheckedError` to throw

### ISSUE THREAD

**Issue by diosney** [zefoy/ngx-fabric-wrapper#6]
To test it, just add a button that updates `[data]`, and set an event like `(selectionUpdated)` to update a property like `isSelected: boolean`, all that in the component that holds the `<fabric>` declaration.

As soon as you trigger the button, the data gets updated, triggers the event, thus updating the property, so the changes detection assumes (correctly) that the changes are bubbling up so it throws the error.

I fixed it in my side in the event callback by delaying the child updates to the next changes detection cycle, as it should be done, by adding `setTimeout` to it, so it triggers a new microtask (the setTimeout workaround is a naive one but effective, and there are others ways to fix it). 

Is true that this can be fixed on client code outside the fabric component, like I did, but could be nice if a proper solution gets added into the component itself, since the magnitude of the possible issue (I had to add the setTimeout to every single event I had).

**Comment by sconix** [comment]
This should be fixed in the new 8.0.0 release.
