### ISSUE TITLE
objectScaled and objectMoved don't emit any event

### ISSUE THREAD

**Issue by qwe852147** [zefoy/ngx-fabric-wrapper#8]
I want get objectScaled  and objectMoved event but i can't get any event after object scale and move.

I create example [stackblitz](https://stackblitz.com/edit/github-3w297h?file=projects%2Fapp%2Fsrc%2Fapp%2Fapp.component.html),changeTest function don't fire after scaled and moved.

**Comment by AsimNet** [comment]
same here
objectMoved doesn't work

**Comment by sconix** [comment]
Will release a bug fix update for this. The events have been working in directive but not in component.

**Comment by sconix** [comment]
Should be fixex in 9.1.0 release.
